### PR TITLE
repl output whitespace formatting

### LINKED ISSUE #6: basic formatting for repl output
lines sent to the repl are broken on \n but other formatting characters such as \t are passed through (and subsequently ignored by browser layout engine)

### PR DESCRIPTION
**Pull request by pq**
possibly a naive fix, but tabs at least look good.

image

let me know if i'm missing anything or if there's a better approach.

fixes #6 

/cc @ngwese

### CODE REVIEW

**Comment by pq** [comment]
well, i said it was naive! 😉 

i think historically there were issues w/ some browsers not being consistent on `tab-width` implementation but maybe modern browsers are all caught up?  as for what to `pre`, i'm sure you're right that the top-level `div` is probably not the ideal place and that each output line is probably better.  i can update that.

as for testing this out.  are there concrete cases you have in mind i could use to convince myself that we've got it right?  admittedly, my driving example is a little bogus.

also, 2 is probably a little tight for tab width; maybe we should opt for 4?  (the standard of 8 seems insane.)

cc @anthonybarsotti for any perspectives...

**Comment by anthonybarsotti** [comment]
I think using `pre` tags would be the right solution for sure. As for `tab-size` though, the browser support for that property seems pretty poor right now so we might want to find a different solution.

**Comment by tehn** [comment]
@pq this is incredibly helpful functionality, thank you!

**Comment by anthonybarsotti** [comment]
I think this solution is great yeah! If we do decide to override the defaults it might be worth making it a user-defined setting with a four space default. For now this looks perfect though.

**Pull request merged**
