### PR TITLE
Integrate eslint and prettier

### PR DESCRIPTION
**Pull request by Jwhiles**
This PR integrates prettier into eslint, so now running eslint --fix will format code. I've also committed the result of running format as part of this PR.

There are still a number of oustanding linting errors, which I hope to resolve in another PR. after that I think it would be nice if we could format code changes on commit :)

### CODE REVIEW

**Comment by pq** [comment]
Awesome.  See also: #38.

@ngwese: were you still planning to do a round of lint cleanups?

**Comment by Jwhiles** [comment]
@pq I've pushed a number of lint fixes - let me know if you don't think they belong in this PR. I also added a single basic test around a function because I wanted to refactor it but wasn't initially sure what it was doing :)

There is only one linting error remaining - relating to a div with a click handler. I think we can just change that element into a button - but I don't feel confident making arbitrary changes to JSX without more thorough manual testing.

**Comment by pq** [comment]
awesome.  thanks @Jwhiles!  i'd like to defer to @ngwese who had mentioned wanting to do a round of cleanups.  (i'm fine with wherever they come in!)  once they're there i can pickup on #37 .

**Comment by pq** [comment]
aside: for development i use vscode (w/ the eslint plugin which provides an action to auto-fix).  any recommendations for setting up the best flow?

**Comment by ngwese** [comment]
@pq - just go for it. i’m not going to be able to get to it.

**Comment by Jwhiles** [comment]
@pq I believe that there's also a prettier plugin for vscode -  I'm not sure how the two plugins would interact, but it's a pretty typical set up so I think it should just work. Personally I've bound `\p` to format with prettier - and I just tend to run it intermittently whilst I'm coding :)

**Comment by pq** [comment]
Thanks @Jwhiles!  I *think* the elsint one is doing all the right things but will update.

Any tips on setting up a good dev environment are always appreciated.  JS is not even close to my first language! 😄

**Pull request merged**
