### PR TITLE
dark editor mode 😎 

### PR DESCRIPTION
**Pull request by pq**
norns dark editor mode 

* 🕶  introduces a new norns dark mode editor theme (“norns_dark”), based on “tomorrow night” (w/ error style borrowed from “chaos”); refinements tracked in #122
* 🕶  adds dark mode aware styling of completion and documentation pop-ups
* 🕶  adds a new editor config to toggle modes (light / “dawn” remains default)
* 🎆  **anti-aliases all text** (where supported; sorry windows ☹️ )

a few visuals.

anti-aliasing and error marking:

image

dark mode popup styling:

image

editor config:

image

whole enchilada:

image

fixes: #33 

@jlmitch5: i **_think_** i wired up the config stuff right but would love confirmation

/cc @ngwese @simonvanderveldt

### CODE REVIEW

**Comment by jlmitch5** [comment]
just took a peak at the config code @pq that looks great and this feature looks awesome!

**Comment by jlmitch5** [comment]
I will double check my modal pr and make sure it works good with this.  I'm sorry for dropping the ball on that @ngwese I will get back to it, promise!!

**Comment by ngwese** [comment]
just run `yarn build` then copy the resulting files over into the maiden directory on the device

**Comment by pq** [comment]
@jlmitch5: let me know how it goes and needless to say any tweaks are absolutely welcome.  chime in here or on #122 👍

**Pull request merged**
